# Generated by Django 2.2 on 2020-05-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
