# Generated by Django 2.2 on 2020-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200506_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='semester',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='calculator',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
