# Generated by Django 2.2 on 2020-05-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email',
            new_name='username',
        ),
    ]
