# Generated by Django 2.2 on 2020-05-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20200511_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='addmission',
            field=models.CharField(default='', max_length=4, null=True),
        ),
    ]
