# Generated by Django 2.2 on 2020-05-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_account_addmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='major',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='addmission',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
