# Generated by Django 2.2 on 2020-05-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20200512_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
