# Generated by Django 2.2 on 2020-05-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_category',
            field=models.CharField(default='전공', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_year',
            field=models.IntegerField(null=True),
        ),
    ]
