# Generated by Django 2.2 on 2020-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200522_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_year',
            field=models.IntegerField(default='2020', null=True),
        ),
    ]
